// ---------------------------------------------------------------------------
//  gemm_vk_bench - Vulkan compute SGEMM benchmark for Android (arm64-v8a)
//
//  Measures C[MxN] = A[MxK] * B[KxN] (fp32, row-major) with four kernel
//  variants that differ ONLY in how the A/B operands are fed to the FMA loop:
//
//     none       A: global memory   B: global memory
//     shared_a   A: shared memory   B: global memory
//     shared_b   A: global memory   B: shared memory
//     shared_ab  A: shared memory   B: shared memory
//
//  Two run modes:
//     --mode perf   (default) pure performance, results are never read back
//     --mode check  verify the GPU result against a CPU reference
// ---------------------------------------------------------------------------

#include <vulkan/vulkan.h>

#include <algorithm>
#include <chrono>
#include <cmath>
#include <cstdarg>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <functional>
#include <random>
#include <string>
#include <thread>
#include <vector>

// SPIR-V for every (staging variant, micro-tile) pair, generated by
// glslc -O -mfmt=c at build time. See CMakeLists.txt.
#include "shaders_table.h"

// Must match the shader's compile-time constants.
static const uint32_t kTS    = 16;  // workgroup is kTS x kTS invocations
static const uint32_t kTileK = 16;  // BK, the K-tile depth

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------

static void die(const char* fmt, ...)
{
    va_list ap;
    va_start(ap, fmt);
    fprintf(stderr, "ERROR: ");
    vfprintf(stderr, fmt, ap);
    fprintf(stderr, "\n");
    va_end(ap);
    exit(1);
}

static const char* vkResultStr(VkResult r)
{
    switch (r) {
    case VK_SUCCESS:                        return "VK_SUCCESS";
    case VK_NOT_READY:                      return "VK_NOT_READY";
    case VK_TIMEOUT:                        return "VK_TIMEOUT";
    case VK_ERROR_OUT_OF_HOST_MEMORY:       return "VK_ERROR_OUT_OF_HOST_MEMORY";
    case VK_ERROR_OUT_OF_DEVICE_MEMORY:     return "VK_ERROR_OUT_OF_DEVICE_MEMORY";
    case VK_ERROR_INITIALIZATION_FAILED:    return "VK_ERROR_INITIALIZATION_FAILED";
    case VK_ERROR_DEVICE_LOST:              return "VK_ERROR_DEVICE_LOST";
    case VK_ERROR_LAYER_NOT_PRESENT:        return "VK_ERROR_LAYER_NOT_PRESENT";
    case VK_ERROR_EXTENSION_NOT_PRESENT:    return "VK_ERROR_EXTENSION_NOT_PRESENT";
    case VK_ERROR_FEATURE_NOT_PRESENT:      return "VK_ERROR_FEATURE_NOT_PRESENT";
    case VK_ERROR_INCOMPATIBLE_DRIVER:      return "VK_ERROR_INCOMPATIBLE_DRIVER";
    case VK_ERROR_FRAGMENTED_POOL:          return "VK_ERROR_FRAGMENTED_POOL";
    case VK_ERROR_OUT_OF_POOL_MEMORY:       return "VK_ERROR_OUT_OF_POOL_MEMORY";
    default:                                return "VK_ERROR_<other>";
    }
}

#define VK_CHECK(expr)                                                        \
    do {                                                                      \
        VkResult _r = (expr);                                                 \
        if (_r != VK_SUCCESS)                                                 \
            die("%s failed at %s:%d -> %s (%d)", #expr, __FILE__, __LINE__,   \
                vkResultStr(_r), (int)_r);                                    \
    } while (0)

static double nowSeconds()
{
    using clock = std::chrono::steady_clock;
    return std::chrono::duration<double>(clock::now().time_since_epoch()).count();
}

// GFLOP per millisecond IS TFLOP/s: 1e9 FLOP / 1e-3 s = 1e12 FLOP/s.
// Kept as one function because open-coding it is what let an extra /1e3 spread
// to five call sites and report every result 1000x low.
static constexpr double tflops(double gflop, double ms)
{
    return (ms > 0.0) ? gflop / ms : 0.0;
}

// 2048^3 GEMM is 17.179869184 GFLOP; at 20 ms that is 0.859 TFLOP/s.
static_assert(tflops(17.179869184, 20.0) > 0.8589 &&
              tflops(17.179869184, 20.0) < 0.8591,
              "TFLOPS unit conversion is wrong: GFLOP/ms already equals TFLOP/s");

static double median(std::vector<double> v)
{
    if (v.empty()) return 0.0;
    std::sort(v.begin(), v.end());
    size_t n = v.size();
    return (n & 1) ? v[n / 2] : 0.5 * (v[n / 2 - 1] + v[n / 2]);
}

// ---------------------------------------------------------------------------
// kernel table
// ---------------------------------------------------------------------------

struct KernelDesc {
    const char*     name;      // staging variant: none / shared_a / shared_b / shared_ab
    const char*     aSrc;
    const char*     bSrc;
    const char*     aLayout;   // "col" (A uploaded transposed) or "row"
    uint32_t        tm;        // rows of C per invocation
    uint32_t        tn;        // cols of C per invocation
    uint32_t        db;        // 1 = LDS tiles are ping-ponged
    uint32_t        bsplit;    // 0 = one run of TN columns per invocation,
                               // else the group size the run is split into
    const uint32_t* spv;
    size_t          spvBytes;

    uint32_t blockM() const { return kTS * tm; }   // BM
    uint32_t blockN() const { return kTS * tn; }   // BN
    bool     aCol()   const { return aLayout[0] == 'c'; }
    // Fully unrolled inner loop is BK * TM * TN fused multiply-adds.
    uint32_t expectedFma() const { return kTileK * tm * tn; }
    // LDS bytes. The row-major A staging store needs a pad, column-major does
    // not; double buffering holds two of every tile.
    uint32_t ldsBytes() const {
        uint32_t n = 0;
        if (aSrc[0] == 's') n += kTileK * (blockM() + (aCol() ? 0u : 4u)) * 4u;
        if (bSrc[0] == 's') n += kTileK * blockN() * 4u;
        return n * (db ? 2u : 1u);
    }
    // Per-invocation prefetch registers held across the compute phase.
    uint32_t prefetchRegs() const {
        if (!db) return 0;
        uint32_t n = 0;
        if (aSrc[0] == 's') n += (kTileK * blockM()) / (kTS * kTS);
        if (bSrc[0] == 's') n += (kTileK * blockN()) / (kTS * kTS);
        return n;
    }
};

static const KernelDesc kKernels[] = { GEMM_KERNEL_TABLE };
static const int kNumKernels = (int)(sizeof(kKernels) / sizeof(kKernels[0]));

#ifndef GEMM_BENCH_VERSION
#define GEMM_BENCH_VERSION "dev"
#endif

static const uint32_t kDefaultTM = 4;
static const uint32_t kDefaultTN = 4;
static const char*    kDefaultALayout = "col";

// Group size of the split B column mapping. Must match B_SPLITS in CMakeLists.
static const uint32_t kBSplitGroup = 4;

// Only built where the split mapping actually differs from the linear one: TN
// has to be a multiple of the group size and hold more than one group, so TN=4
// and TN=6 have no split build and asking for one is not an error.
static bool bSplitBuilt(uint32_t tn)
{
    return (tn % kBSplitGroup) == 0 && tn > kBSplitGroup;
}

// Walk the embedded SPIR-V and count GLSL.std.450 Fma instructions.
//
// This is the build's own smoke test. Without shader optimization the inner
// loop stays rolled and the accumulators live in scratch memory, which costs
// ~1000x; the giveaway is that the whole module contains a single Fma instead
// of BK*TM*TN. Printing this at startup makes a stale or mis-built binary
// obvious from the log alone, instead of looking like a hardware result.
static uint32_t countFma(const uint32_t* spv, size_t bytes)
{
    const size_t n = bytes / sizeof(uint32_t);
    if (n < 5 || spv[0] != 0x07230203u) return UINT32_MAX;   // not SPIR-V

    uint32_t count = 0;
    for (size_t i = 5; i < n; ) {
        const uint32_t wordCount = spv[i] >> 16;
        const uint32_t opcode    = spv[i] & 0xFFFFu;
        if (wordCount == 0 || i + wordCount > n) break;       // malformed
        // OpExtInst: [0]=hdr [1]=type [2]=result [3]=set [4]=instruction literal
        if (opcode == 12u && wordCount >= 5 && spv[i + 4] == 50u /* Fma */)
            ++count;
        i += wordCount;
    }
    return count;
}

// ---------------------------------------------------------------------------
// options
// ---------------------------------------------------------------------------

// One benchmark case: C[MxN] = A[MxK] * B[KxN]. Only K has to divide the K tile;
// M and N are free, the shader guards the store.
struct Shape {
    uint32_t m = 0, n = 0, k = 0;
    double gflop() const { return 2.0 * (double)m * (double)n * (double)k / 1e9; }
};

// "S" is the square SxSxS case. "MxKxN" reads in the order the operands do, so
// 576x160x960 is A 576x160 times B 160x960 -- the same string you would write
// the product as.
static Shape parseShape(const std::string& s)
{
    Shape sh;
    unsigned m = 0, k = 0, n = 0;
    int used = 0;
    if (sscanf(s.c_str(), "%ux%ux%u%n", &m, &k, &n, &used) == 3 && used == (int)s.size()) {
        sh.m = m; sh.k = k; sh.n = n;
        return sh;
    }
    char* end = nullptr;
    unsigned long sq = strtoul(s.c_str(), &end, 10);
    if (end == s.c_str() || *end != '\0')
        die("--sizes takes S or MxKxN (got '%s')", s.c_str());
    sh.m = sh.n = sh.k = (uint32_t)sq;
    return sh;
}

struct Options {
    // A 576x160 * B 160x960 -> C 576x960.
    std::vector<Shape> shapes{ Shape{ /*m*/ 576, /*n*/ 960, /*k*/ 160 } };
    std::vector<std::string> variants{ "none", "shared_a", "shared_b", "shared_ab" };
    std::vector<std::pair<uint32_t, uint32_t>> tiles;   // (TM,TN); filled in below
    std::vector<std::string> aLayouts;                  // "col" and/or "row"
    std::vector<int>      dbModes;                      // 0 and/or 1
    std::vector<int>      bSplits;                      // 0 and/or kBSplitGroup
    std::vector<int>      kernels;                      // resolved indices into kKernels
    bool        sweep       = false;
    int         iters       = 5;
    int         warmup      = 2;
    bool        check       = false;   // --mode check
    bool        fullCheck   = false;   // full CPU reference instead of sampled
    int         samples     = 4096;
    int         deviceIndex = -1;
    bool        validation  = false;
    bool        listDevices = false;
    uint32_t    seed        = 12345u;
    std::string csvPath;
};

static void usage(const char* argv0)
{
    printf(
"Vulkan GEMM benchmark (fp32, C = A*B) for Android GPUs\n"
"\n"
"Usage: %s [options]\n"
"\n"
"  --mode <perf|check>   perf  = timing only, results are not read back (default)\n"
"                        check = verify GPU results against a CPU reference\n"
"  --sizes <list>        comma separated shapes, default 576x160x960.\n"
"                        MxKxN is A MxK times B KxN; a bare S means SxSxS\n"
"  --iters <n>           timed iterations per kernel, default 5\n"
"  --warmup <n>          untimed warmup iterations, default 2\n"
"  --kernels <list>      subset of: none,shared_a,shared_b,shared_ab (default all)\n"
"  --tile <TMxTN>        micro-tile per invocation, default 4x4. Repeatable.\n"
"  --a-layout <l>        storage order of A: col (default), row, or both.\n"
"                        col uploads A transposed; B and C are always row-major\n"
"  --double-buffer <d>   LDS tile ping-pong: both (default), on, or off.\n"
"                        no effect on the 'none' variant, which uses no LDS\n"
"  --b-split <s>         B column mapping: both (default), on, or off.\n"
"                        on splits an invocation's TN columns into groups of\n"
"                        4 spread across the block tile, so a wave's loads for\n"
"                        one group are contiguous. Only built for TN=8\n"
"  --sweep               run every built (TM,TN) pair and rank the results\n"
"  --samples <n>         check mode: random output elements to verify (default 4096)\n"
"  --full-check          check mode: verify every element with a CPU GEMM (slow)\n"
"  --device <idx>        physical device index, default: first non-CPU device\n"
"  --list-devices        print available Vulkan devices and exit\n"
"  --validation          enable VK_LAYER_KHRONOS_validation\n"
"  --seed <n>            RNG seed for the input matrices, default 12345\n"
"  --csv <path>          also append the per-run results to a CSV file\n"
"  -h, --help            this text\n"
"\n"
"Kernel variants (identical tiling, only the operand staging differs):\n"
"  none       A global,  B global   - no shared memory at all\n"
"  shared_a   A shared,  B global\n"
"  shared_b   A global,  B shared\n"
"  shared_ab  A shared,  B shared\n"
"\n"
"Built micro-tiles (workgroup is fixed at %ux%u invocations, so the block tile\n"
"is %u*TM x %u*TN):\n",
        argv0, kTS, kTS, kTS, kTS);

    uint32_t lastTm = 0, lastTn = 0;
    for (int k = 0; k < kNumKernels; ++k) {
        if (kKernels[k].tm == lastTm && kKernels[k].tn == lastTn) continue;
        lastTm = kKernels[k].tm;
        lastTn = kKernels[k].tn;
        printf("  %ux%u -> block %ux%u, %u FMA per k-step\n", lastTm, lastTn,
               kKernels[k].blockM(), kKernels[k].blockN(), lastTm * lastTn);
    }
}

static std::vector<std::string> splitList(const char* s)
{
    std::vector<std::string> out;
    std::string cur;
    for (const char* p = s; ; ++p) {
        if (*p == ',' || *p == '\0') {
            if (!cur.empty()) out.push_back(cur);
            cur.clear();
            if (*p == '\0') break;
        } else {
            cur.push_back(*p);
        }
    }
    return out;
}

static Options parseArgs(int argc, char** argv)
{
    Options o;
    auto need = [&](int i, const char* what) {
        if (i + 1 >= argc) die("%s expects an argument", what);
        return argv[i + 1];
    };

    for (int i = 1; i < argc; ++i) {
        std::string a = argv[i];
        if (a == "-h" || a == "--help") { usage(argv[0]); exit(0); }
        else if (a == "--version" || a == "-V") {
            printf("gemm_vk_bench %s (built %s %s)\n", GEMM_BENCH_VERSION, __DATE__, __TIME__);
            printf("%d kernels embedded (workgroup %ux%u, K-tile %u)\n",
                   kNumKernels, kTS, kTS, kTileK);
            int bad = 0;
            for (int k = 0; k < kNumKernels; ++k) {
                const KernelDesc& kd = kKernels[k];
                uint32_t fma = countFma(kd.spv, kd.spvBytes);
                bool ok = (fma == kd.expectedFma());
                if (!ok) ++bad;
                printf("  %-10s %ux%u A-%s %-6s %-4s block %3ux%-3u LDS %5uB pre %2u  "
                       "%6u B  %5u Fma (expect %5u) %s\n",
                       kd.name, kd.tm, kd.tn, kd.aLayout, kd.db ? "db" : "single",
                       kd.bsplit ? "bs4" : "bs-",
                       kd.blockM(), kd.blockN(), kd.ldsBytes(), kd.prefetchRegs(),
                       (unsigned)kd.spvBytes, fma, kd.expectedFma(),
                       ok ? "ok" : "MISMATCH");
            }
            printf("%s\n", bad ? "*** some shaders are not optimized; rebuild with glslc -O ***"
                               : "all shaders optimized");
            exit(bad ? 1 : 0);
        }
        else if (a == "--mode") {
            std::string m = need(i, "--mode"); ++i;
            if (m == "perf")       o.check = false;
            else if (m == "check") o.check = true;
            else die("unknown mode '%s' (expected perf or check)", m.c_str());
        }
        else if (a == "--sizes") {
            o.shapes.clear();
            for (auto& s : splitList(need(i, "--sizes"))) o.shapes.push_back(parseShape(s));
            ++i;
            if (o.shapes.empty()) die("--sizes list is empty");
        }
        else if (a == "--kernels") {
            o.variants.clear();
            for (auto& s : splitList(need(i, "--kernels"))) {
                bool known = false;
                for (int k = 0; k < kNumKernels; ++k)
                    if (s == kKernels[k].name) known = true;
                if (!known) die("unknown kernel '%s'", s.c_str());
                o.variants.push_back(s);
            }
            ++i;
            if (o.variants.empty()) die("--kernels list is empty");
        }
        else if (a == "--tile") {
            const char* s = need(i, "--tile"); ++i;
            unsigned tm = 0, tn = 0;
            if (sscanf(s, "%ux%u", &tm, &tn) != 2 || tm == 0 || tn == 0)
                die("--tile expects TMxTN, e.g. 8x8 (got '%s')", s);
            o.tiles.push_back({ tm, tn });
        }
        else if (a == "--a-layout") {
            std::string l = need(i, "--a-layout"); ++i;
            o.aLayouts.clear();
            if (l == "col" || l == "row")      o.aLayouts.push_back(l);
            else if (l == "both")              o.aLayouts = { "col", "row" };
            else die("--a-layout expects col, row or both (got '%s')", l.c_str());
        }
        else if (a == "--double-buffer") {
            std::string d = need(i, "--double-buffer"); ++i;
            o.dbModes.clear();
            if (d == "on")        o.dbModes = { 1 };
            else if (d == "off")  o.dbModes = { 0 };
            else if (d == "both") o.dbModes = { 0, 1 };
            else die("--double-buffer expects on, off or both (got '%s')", d.c_str());
        }
        else if (a == "--b-split") {
            std::string b = need(i, "--b-split"); ++i;
            o.bSplits.clear();
            if (b == "on")        o.bSplits = { (int)kBSplitGroup };
            else if (b == "off")  o.bSplits = { 0 };
            else if (b == "both") o.bSplits = { 0, (int)kBSplitGroup };
            else die("--b-split expects on, off or both (got '%s')", b.c_str());
        }
        else if (a == "--sweep")        { o.sweep = true; }
        else if (a == "--iters")        { o.iters = atoi(need(i, "--iters")); ++i; }
        else if (a == "--warmup")       { o.warmup = atoi(need(i, "--warmup")); ++i; }
        else if (a == "--samples")      { o.samples = atoi(need(i, "--samples")); ++i; }
        else if (a == "--full-check")   { o.fullCheck = true; o.check = true; }
        else if (a == "--device")       { o.deviceIndex = atoi(need(i, "--device")); ++i; }
        else if (a == "--list-devices") { o.listDevices = true; }
        else if (a == "--validation")   { o.validation = true; }
        else if (a == "--seed")         { o.seed = (uint32_t)strtoul(need(i, "--seed"), nullptr, 10); ++i; }
        else if (a == "--csv")          { o.csvPath = need(i, "--csv"); ++i; }
        else die("unknown option '%s' (try --help)", a.c_str());
    }

    if (o.iters  < 1) die("--iters must be >= 1");
    if (o.warmup < 0) die("--warmup must be >= 0");
    for (const Shape& s : o.shapes) {
        if (!s.m || !s.n || !s.k) die("matrix dimensions must be > 0");
        // Only K has to divide evenly: the k loop walks whole BK tiles. A
        // partial M/N tile is handled by the guarded store in the shader.
        if (s.k % kTileK)
            die("K = %u must be a multiple of the K tile (%u)", s.k, kTileK);
    }

    // Resolve (layout, tile, variant, buffering, B mapping) combinations into
    // built kernel indices.
    if (o.tiles.empty()) {
        if (o.sweep) {
            for (int k = 0; k < kNumKernels; ++k) {
                auto t = std::make_pair(kKernels[k].tm, kKernels[k].tn);
                if (std::find(o.tiles.begin(), o.tiles.end(), t) == o.tiles.end())
                    o.tiles.push_back(t);
            }
        } else {
            o.tiles.push_back({ kDefaultTM, kDefaultTN });
        }
    }
    if (o.aLayouts.empty()) o.aLayouts.push_back(kDefaultALayout);
    if (o.dbModes.empty())  o.dbModes = { 0, 1 };
    if (o.bSplits.empty())  o.bSplits = { 0, (int)kBSplitGroup };

    // Layout is the outermost loop: switching it means re-uploading A, so this
    // ordering keeps that to one upload per layout per shape. The B mapping is
    // innermost so its two builds sit next to each other in the output.
    for (const std::string& lay : o.aLayouts) {
        for (auto& t : o.tiles) {
            for (const std::string& v : o.variants) {
                for (int db : o.dbModes) {
                    for (int bs : o.bSplits) {
                        int found = -1;
                        for (int k = 0; k < kNumKernels; ++k)
                            if (v == kKernels[k].name && kKernels[k].aLayout == lay &&
                                kKernels[k].tm == t.first && kKernels[k].tn == t.second &&
                                (int)kKernels[k].db == db && (int)kKernels[k].bsplit == bs)
                                found = k;
                        // "none" has no LDS, so no db=1 build exists; that is not
                        // an error, there is simply nothing to ping-pong.
                        if (found < 0 && db == 1 && v == "none") continue;
                        // Likewise a TN that cannot be split into more than one
                        // group has only the one mapping.
                        if (found < 0 && bs != 0 && !bSplitBuilt(t.second)) continue;
                        if (found < 0)
                            die("no kernel built for %s tile %ux%u A-%s db=%d bsplit=%d (see --help)",
                                v.c_str(), t.first, t.second, lay.c_str(), db, bs);
                        o.kernels.push_back(found);
                    }
                }
            }
        }
    }
    if (o.kernels.empty()) die("nothing to run");
    return o;
}

// ---------------------------------------------------------------------------
// Vulkan context
// ---------------------------------------------------------------------------

struct VulkanCtx {
    VkInstance                       instance   = VK_NULL_HANDLE;
    VkPhysicalDevice                 phys       = VK_NULL_HANDLE;
    VkDevice                         device     = VK_NULL_HANDLE;
    VkQueue                          queue      = VK_NULL_HANDLE;
    uint32_t                         queueFamily = 0;
    uint32_t                         timestampValidBits = 0;
    VkPhysicalDeviceProperties       props{};
    VkPhysicalDeviceMemoryProperties memProps{};
    VkCommandPool                    cmdPool    = VK_NULL_HANDLE;
    VkQueryPool                      queryPool  = VK_NULL_HANDLE;
    std::string                      driverName;
    std::string                      driverInfo;
};

static const char* devTypeStr(VkPhysicalDeviceType t)
{
    switch (t) {
    case VK_PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU: return "integrated GPU";
    case VK_PHYSICAL_DEVICE_TYPE_DISCRETE_GPU:   return "discrete GPU";
    case VK_PHYSICAL_DEVICE_TYPE_VIRTUAL_GPU:    return "virtual GPU";
    case VK_PHYSICAL_DEVICE_TYPE_CPU:            return "CPU";
    default:                                     return "other";
    }
}

static void createInstance(VulkanCtx& ctx, const Options& o)
{
    VkApplicationInfo app{ VK_STRUCTURE_TYPE_APPLICATION_INFO };
    app.pApplicationName = "gemm_vk_bench";
    app.apiVersion       = VK_API_VERSION_1_1;

    std::vector<const char*> layers;
    if (o.validation) {
        uint32_t n = 0;
        vkEnumerateInstanceLayerProperties(&n, nullptr);
        std::vector<VkLayerProperties> lp(n);
        vkEnumerateInstanceLayerProperties(&n, lp.data());
        bool have = false;
        for (auto& l : lp)
            if (!strcmp(l.layerName, "VK_LAYER_KHRONOS_validation")) have = true;
        if (have) layers.push_back("VK_LAYER_KHRONOS_validation");
        else fprintf(stderr, "WARNING: VK_LAYER_KHRONOS_validation not available, continuing without it\n");
    }

    VkInstanceCreateInfo ci{ VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO };
    ci.pApplicationInfo        = &app;
    ci.enabledLayerCount       = (uint32_t)layers.size();
    ci.ppEnabledLayerNames     = layers.data();

    VkResult r = vkCreateInstance(&ci, nullptr, &ctx.instance);
    if (r == VK_ERROR_INCOMPATIBLE_DRIVER) {
        // Fall back to a 1.0 instance on older loaders.
        app.apiVersion = VK_API_VERSION_1_0;
        r = vkCreateInstance(&ci, nullptr, &ctx.instance);
    }
    if (r != VK_SUCCESS) die("vkCreateInstance failed: %s", vkResultStr(r));
}

static void queryDriverInfo(VulkanCtx& ctx)
{
    if (ctx.props.apiVersion < VK_API_VERSION_1_1) return;
    auto fp = (PFN_vkGetPhysicalDeviceProperties2)
        vkGetInstanceProcAddr(ctx.instance, "vkGetPhysicalDeviceProperties2");
    if (!fp) return;

    VkPhysicalDeviceDriverProperties drv{ VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DRIVER_PROPERTIES };
    VkPhysicalDeviceProperties2 p2{ VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PROPERTIES_2 };
    p2.pNext = &drv;
    fp(ctx.phys, &p2);
    ctx.driverName = drv.driverName;
    ctx.driverInfo = drv.driverInfo;
}

static void pickDevice(VulkanCtx& ctx, const Options& o)
{
    uint32_t n = 0;
    VK_CHECK(vkEnumeratePhysicalDevices(ctx.instance, &n, nullptr));
    if (n == 0) die("no Vulkan physical device found");
    std::vector<VkPhysicalDevice> devs(n);
    VK_CHECK(vkEnumeratePhysicalDevices(ctx.instance, &n, devs.data()));

    if (o.listDevices) {
        printf("Vulkan physical devices (%u):\n", n);
        for (uint32_t i = 0; i < n; ++i) {
            VkPhysicalDeviceProperties p;
            vkGetPhysicalDeviceProperties(devs[i], &p);
            printf("  [%u] %-40s  %-15s  API %u.%u.%u\n", i, p.deviceName, devTypeStr(p.deviceType),
                   VK_VERSION_MAJOR(p.apiVersion), VK_VERSION_MINOR(p.apiVersion), VK_VERSION_PATCH(p.apiVersion));
        }
        exit(0);
    }

    int pick = o.deviceIndex;
    if (pick < 0) {
        pick = 0;
        for (uint32_t i = 0; i < n; ++i) {
            VkPhysicalDeviceProperties p;
            vkGetPhysicalDeviceProperties(devs[i], &p);
            if (p.deviceType != VK_PHYSICAL_DEVICE_TYPE_CPU) { pick = (int)i; break; }
        }
    }
    if (pick >= (int)n) die("--device %d out of range (%u devices)", pick, n);

    ctx.phys = devs[pick];
    vkGetPhysicalDeviceProperties(ctx.phys, &ctx.props);
    vkGetPhysicalDeviceMemoryProperties(ctx.phys, &ctx.memProps);
    queryDriverInfo(ctx);
}

static void createDevice(VulkanCtx& ctx)
{
    uint32_t n = 0;
    vkGetPhysicalDeviceQueueFamilyProperties(ctx.phys, &n, nullptr);
    std::vector<VkQueueFamilyProperties> qf(n);
    vkGetPhysicalDeviceQueueFamilyProperties(ctx.phys, &n, qf.data());

    // Prefer a compute-only family (async compute); fall back to any compute queue.
    int chosen = -1;
    for (uint32_t i = 0; i < n; ++i)
        if ((qf[i].queueFlags & VK_QUEUE_COMPUTE_BIT) && !(qf[i].queueFlags & VK_QUEUE_GRAPHICS_BIT)) { chosen = (int)i; break; }
    if (chosen < 0)
        for (uint32_t i = 0; i < n; ++i)
            if (qf[i].queueFlags & VK_QUEUE_COMPUTE_BIT) { chosen = (int)i; break; }
    if (chosen < 0) die("no compute-capable queue family");

    ctx.queueFamily        = (uint32_t)chosen;
    ctx.timestampValidBits = qf[chosen].timestampValidBits;

    float prio = 1.0f;
    VkDeviceQueueCreateInfo qci{ VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO };
    qci.queueFamilyIndex = ctx.queueFamily;
    qci.queueCount       = 1;
    qci.pQueuePriorities = &prio;

    VkDeviceCreateInfo dci{ VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO };
    dci.queueCreateInfoCount = 1;
    dci.pQueueCreateInfos    = &qci;

    VK_CHECK(vkCreateDevice(ctx.phys, &dci, nullptr, &ctx.device));
    vkGetDeviceQueue(ctx.device, ctx.queueFamily, 0, &ctx.queue);

    VkCommandPoolCreateInfo cpi{ VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO };
    cpi.flags            = VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT;
    cpi.queueFamilyIndex = ctx.queueFamily;
    VK_CHECK(vkCreateCommandPool(ctx.device, &cpi, nullptr, &ctx.cmdPool));

    if (ctx.timestampValidBits > 0) {
        VkQueryPoolCreateInfo qpi{ VK_STRUCTURE_TYPE_QUERY_POOL_CREATE_INFO };
        qpi.queryType  = VK_QUERY_TYPE_TIMESTAMP;
        qpi.queryCount = 2;
        VK_CHECK(vkCreateQueryPool(ctx.device, &qpi, nullptr, &ctx.queryPool));
    }
}

// ---------------------------------------------------------------------------
// buffers
// ---------------------------------------------------------------------------

struct Buffer {
    VkBuffer       buf  = VK_NULL_HANDLE;
    VkDeviceMemory mem  = VK_NULL_HANDLE;
    VkDeviceSize   size = 0;
    void*          host = nullptr;
};

static uint32_t findMemoryType(const VulkanCtx& ctx, uint32_t typeBits, VkMemoryPropertyFlags want)
{
    for (uint32_t i = 0; i < ctx.memProps.memoryTypeCount; ++i)
        if ((typeBits & (1u << i)) && (ctx.memProps.memoryTypes[i].propertyFlags & want) == want)
            return i;
    return UINT32_MAX;
}

static Buffer createBuffer(const VulkanCtx& ctx, VkDeviceSize size,
                           VkBufferUsageFlags usage, VkMemoryPropertyFlags want,
                           const char* what)
{
    Buffer b;
    b.size = size;

    VkBufferCreateInfo bi{ VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO };
    bi.size        = size;
    bi.usage       = usage;
    bi.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
    VK_CHECK(vkCreateBuffer(ctx.device, &bi, nullptr, &b.buf));

    VkMemoryRequirements req;
    vkGetBufferMemoryRequirements(ctx.device, b.buf, &req);

    uint32_t type = findMemoryType(ctx, req.memoryTypeBits, want);
    if (type == UINT32_MAX && (want & VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT)) {
        // Unified-memory parts may not expose a plain DEVICE_LOCAL type.
        type = findMemoryType(ctx, req.memoryTypeBits, 0);
    }
    if (type == UINT32_MAX) die("no suitable memory type for %s (%.1f MiB)", what, size / 1048576.0);

    VkMemoryAllocateInfo ai{ VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO };
    ai.allocationSize  = req.size;
    ai.memoryTypeIndex = type;
    VkResult r = vkAllocateMemory(ctx.device, &ai, nullptr, &b.mem);
    if (r != VK_SUCCESS)
        die("failed to allocate %.1f MiB for %s: %s", size / 1048576.0, what, vkResultStr(r));

    VK_CHECK(vkBindBufferMemory(ctx.device, b.buf, b.mem, 0));

    if (ctx.memProps.memoryTypes[type].propertyFlags & VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT)
        VK_CHECK(vkMapMemory(ctx.device, b.mem, 0, VK_WHOLE_SIZE, 0, &b.host));

    return b;
}

static void destroyBuffer(const VulkanCtx& ctx, Buffer& b)
{
    if (b.host) { vkUnmapMemory(ctx.device, b.mem); b.host = nullptr; }
    if (b.buf)  { vkDestroyBuffer(ctx.device, b.buf, nullptr); b.buf = VK_NULL_HANDLE; }
    if (b.mem)  { vkFreeMemory(ctx.device, b.mem, nullptr);    b.mem = VK_NULL_HANDLE; }
}

// One-shot command buffer helper: record, submit, wait, free.
static void submitOnce(const VulkanCtx& ctx, const std::function<void(VkCommandBuffer)>& rec)
{
    VkCommandBufferAllocateInfo ai{ VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO };
    ai.commandPool        = ctx.cmdPool;
    ai.level              = VK_COMMAND_BUFFER_LEVEL_PRIMARY;
    ai.commandBufferCount = 1;
    VkCommandBuffer cb;
    VK_CHECK(vkAllocateCommandBuffers(ctx.device, &ai, &cb));

    VkCommandBufferBeginInfo bi{ VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO };
    bi.flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;
    VK_CHECK(vkBeginCommandBuffer(cb, &bi));
    rec(cb);
    VK_CHECK(vkEndCommandBuffer(cb));

    VkFenceCreateInfo fi{ VK_STRUCTURE_TYPE_FENCE_CREATE_INFO };
    VkFence fence;
    VK_CHECK(vkCreateFence(ctx.device, &fi, nullptr, &fence));

    VkSubmitInfo si{ VK_STRUCTURE_TYPE_SUBMIT_INFO };
    si.commandBufferCount = 1;
    si.pCommandBuffers    = &cb;
    VK_CHECK(vkQueueSubmit(ctx.queue, 1, &si, fence));
    VK_CHECK(vkWaitForFences(ctx.device, 1, &fence, VK_TRUE, UINT64_MAX));

    vkDestroyFence(ctx.device, fence, nullptr);
    vkFreeCommandBuffers(ctx.device, ctx.cmdPool, 1, &cb);
}

// ---------------------------------------------------------------------------
// CPU reference
// ---------------------------------------------------------------------------

// Exact dot product for a single output element, accumulated in double.
static double refElement(const float* A, const float* B, uint32_t row, uint32_t col,
                         uint32_t N, uint32_t K)
{
    const float* a = A + (size_t)row * K;
    const float* b = B + col;
    double s = 0.0;
    for (uint32_t k = 0; k < K; ++k)
        s += (double)a[k] * (double)b[(size_t)k * N];
    return s;
}

struct CheckResult {
    double   maxAbs   = 0.0;
    double   maxRel   = 0.0;
    double   rms      = 0.0;
    uint64_t compared = 0;
    uint64_t bad      = 0;
    bool     pass     = true;
};

static void accumulateError(CheckResult& cr, double got, double ref, double atol, double rtol)
{
    double d = std::fabs(got - ref);
    double rel = d / std::max(std::fabs(ref), 1e-30);
    cr.maxAbs = std::max(cr.maxAbs, d);
    if (std::fabs(ref) > 1e-6) cr.maxRel = std::max(cr.maxRel, rel);
    cr.rms += d * d;
    cr.compared++;
    if (d > atol + rtol * std::fabs(ref)) { cr.bad++; cr.pass = false; }
}

static CheckResult checkSampled(const float* A, const float* B, const float* C,
                                uint32_t M, uint32_t N, uint32_t K,
                                int samples, uint32_t seed, double atol, double rtol)
{
    CheckResult cr;
    std::mt19937 rng(seed ^ 0xB1A5u);
    std::uniform_int_distribution<uint32_t> dr(0, M - 1), dc(0, N - 1);

    // Always include the four corners; they catch indexing bugs at the edges.
    std::vector<std::pair<uint32_t, uint32_t>> pts = {
        { 0, 0 }, { 0, N - 1 }, { M - 1, 0 }, { M - 1, N - 1 }
    };
    for (int i = 0; i < samples; ++i) pts.push_back({ dr(rng), dc(rng) });

    for (auto& p : pts) {
        double ref = refElement(A, B, p.first, p.second, N, K);
        double got = (double)C[(size_t)p.first * N + p.second];
        accumulateError(cr, got, ref, atol, rtol);
    }
    cr.rms = std::sqrt(cr.rms / (double)cr.compared);
    return cr;
}

static CheckResult checkFull(const float* A, const float* B, const float* C,
                             uint32_t M, uint32_t N, uint32_t K, double atol, double rtol)
{
    unsigned nt = std::max(1u, std::thread::hardware_concurrency());
    std::vector<CheckResult> parts(nt);
    std::vector<std::thread>  th;

    for (unsigned t = 0; t < nt; ++t) {
        th.emplace_back([&, t]() {
            std::vector<double> row(N);
            for (uint32_t m = t; m < M; m += nt) {
                std::fill(row.begin(), row.end(), 0.0);
                const float* a = A + (size_t)m * K;
                for (uint32_t k = 0; k < K; ++k) {           // i-k-j: cache friendly
                    double av = a[k];
                    if (av == 0.0) continue;
                    const float* b = B + (size_t)k * N;
                    for (uint32_t n = 0; n < N; ++n) row[n] += av * b[n];
                }
                const float* c = C + (size_t)m * N;
                for (uint32_t n = 0; n < N; ++n)
                    accumulateError(parts[t], (double)c[n], row[n], atol, rtol);
            }
        });
    }
    for (auto& x : th) x.join();

    CheckResult cr;
    for (auto& p : parts) {
        cr.maxAbs = std::max(cr.maxAbs, p.maxAbs);
        cr.maxRel = std::max(cr.maxRel, p.maxRel);
        cr.rms   += p.rms;
        cr.compared += p.compared;
        cr.bad      += p.bad;
        cr.pass      = cr.pass && p.pass;
    }
    cr.rms = std::sqrt(cr.rms / (double)std::max<uint64_t>(cr.compared, 1));
    return cr;
}

// ---------------------------------------------------------------------------
// benchmark
// ---------------------------------------------------------------------------

struct RunStats {
    int                 kernel = 0;
    std::vector<double> gpuMs;      // from GPU timestamps (empty if unsupported)
    std::vector<double> wallMs;     // submit -> fence signalled
    bool                checked = false;
    CheckResult         check;
    bool                bitExactVsFirst = false;
    double              maxDiffVsFirst  = 0.0;
};

int main(int argc, char** argv)
{
    Options o = parseArgs(argc, argv);

    VulkanCtx ctx;
    createInstance(ctx, o);
    pickDevice(ctx, o);
    createDevice(ctx);

    const double tsPeriodNs = ctx.props.limits.timestampPeriod;
    const bool   haveTs     = (ctx.queryPool != VK_NULL_HANDLE) && tsPeriodNs > 0.0;

    printf("======================================================================\n");
    printf(" Vulkan GEMM benchmark  (fp32, C[MxN] = A[MxK] * B[KxN], row-major)\n");
    printf(" version %s   built %s %s\n", GEMM_BENCH_VERSION, __DATE__, __TIME__);
    printf("======================================================================\n");
    printf("  Device            : %s\n", ctx.props.deviceName);
    printf("  Type              : %s\n", devTypeStr(ctx.props.deviceType));
    printf("  Vulkan API        : %u.%u.%u\n", VK_VERSION_MAJOR(ctx.props.apiVersion),
           VK_VERSION_MINOR(ctx.props.apiVersion), VK_VERSION_PATCH(ctx.props.apiVersion));
    if (!ctx.driverName.empty())
        printf("  Driver            : %s / %s\n", ctx.driverName.c_str(), ctx.driverInfo.c_str());
    printf("  Vendor/Device ID  : 0x%04x / 0x%04x\n", ctx.props.vendorID, ctx.props.deviceID);
    printf("  Max shared mem/WG : %u bytes\n", ctx.props.limits.maxComputeSharedMemorySize);
    printf("  Max WG invocations: %u\n", ctx.props.limits.maxComputeWorkGroupInvocations);
    if (haveTs)
        printf("  GPU timestamps    : yes (period %.3f ns, %u valid bits)\n", tsPeriodNs, ctx.timestampValidBits);
    else
        printf("  GPU timestamps    : NOT supported - falling back to wall-clock timing\n");
    printf("  Workgroup         : %ux%u invocations, K-tile %u\n", kTS, kTS, kTileK);
    printf("  Mode              : %s\n",
           o.check ? (o.fullCheck ? "CHECK (full CPU reference)" : "CHECK (sampled CPU reference)")
                   : "PERF (results are not verified)");
    printf("  Iterations        : %d timed + %d warmup\n", o.iters, o.warmup);
    printf("  Seed              : %u\n", o.seed);
    printf("\n");

    if (kTS * kTS > ctx.props.limits.maxComputeWorkGroupInvocations)
        die("kernel uses %u invocations per workgroup, device allows %u",
            kTS * kTS, ctx.props.limits.maxComputeWorkGroupInvocations);

    // Drop kernels that do not fit in LDS rather than aborting: double
    // buffering doubles the tile storage, so a sweep can legitimately contain
    // a few combinations this device cannot run.
    {
        std::vector<int> fits;
        for (int kidx : o.kernels) {
            const KernelDesc& kd = kKernels[kidx];
            if (kd.ldsBytes() <= ctx.props.limits.maxComputeSharedMemorySize) {
                fits.push_back(kidx);
            } else {
                printf("  SKIP %s %ux%u A-%s%s%s: needs %u B of LDS, device allows %u\n",
                       kd.name, kd.tm, kd.tn, kd.aLayout, kd.db ? " db" : "",
                       kd.bsplit ? " bs4" : "",
                       kd.ldsBytes(), ctx.props.limits.maxComputeSharedMemorySize);
            }
        }
        if (fits.empty())
            die("every selected kernel exceeds the device shared memory limit (%u bytes)",
                ctx.props.limits.maxComputeSharedMemorySize);
        if (fits.size() != o.kernels.size())
            printf("  (%u kernels skipped)\n\n", (unsigned)(o.kernels.size() - fits.size()));
        o.kernels.swap(fits);
    }

    // Embedded shader self-check over the kernels actually selected (countFma).
    printf("  Kernels selected  : %u of %d built\n", (unsigned)o.kernels.size(), kNumKernels);
    printf("  SPIR-V self-check :");
    int shaderBad = 0;
    for (int kidx : o.kernels) {
        const KernelDesc& kd = kKernels[kidx];
        if (countFma(kd.spv, kd.spvBytes) != kd.expectedFma()) ++shaderBad;
    }
    if (shaderBad == 0) {
        printf(" OK (every selected kernel has BK*TM*TN unrolled FMA)\n");
    } else {
        printf(" %d of %u kernels FAILED\n", shaderBad, (unsigned)o.kernels.size());
        printf("\n");
        printf("  *********************************************************************\n");
        printf("  ** WARNING: shaders are NOT optimized (expect BK*TM*TN Fma each).   **\n");
        printf("  ** The inner loop is still rolled and the accumulators spill to     **\n");
        printf("  ** scratch memory. Results will be ~1000x too slow and are NOT a    **\n");
        printf("  ** property of the GPU. Rebuild with glslc -O.                      **\n");
        printf("  *********************************************************************\n");
    }
    printf("\n");


    // ---- shared pipeline objects -----------------------------------------
    VkDescriptorSetLayoutBinding binds[3]{};
    for (int i = 0; i < 3; ++i) {
        binds[i].binding         = (uint32_t)i;
        binds[i].descriptorType  = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
        binds[i].descriptorCount = 1;
        binds[i].stageFlags      = VK_SHADER_STAGE_COMPUTE_BIT;
    }
    VkDescriptorSetLayoutCreateInfo dli{ VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO };
    dli.bindingCount = 3;
    dli.pBindings    = binds;
    VkDescriptorSetLayout setLayout;
    VK_CHECK(vkCreateDescriptorSetLayout(ctx.device, &dli, nullptr, &setLayout));

    VkPushConstantRange pcr{ VK_SHADER_STAGE_COMPUTE_BIT, 0, 3 * sizeof(uint32_t) };
    VkPipelineLayoutCreateInfo pli{ VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO };
    pli.setLayoutCount         = 1;
    pli.pSetLayouts            = &setLayout;
    pli.pushConstantRangeCount = 1;
    pli.pPushConstantRanges    = &pcr;
    VkPipelineLayout pipeLayout;
    VK_CHECK(vkCreatePipelineLayout(ctx.device, &pli, nullptr, &pipeLayout));

    // Only the selected kernels get a pipeline: compiling all 36 up front costs
    // real seconds on a mobile driver, and a default run needs four of them.
    VkPipeline pipelines[kNumKernels]{};
    std::vector<int> needed = o.kernels;
    std::sort(needed.begin(), needed.end());
    needed.erase(std::unique(needed.begin(), needed.end()), needed.end());

    double pipeT0 = nowSeconds();
    for (int k : needed) {
        VkShaderModuleCreateInfo smi{ VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO };
        smi.codeSize = kKernels[k].spvBytes;
        smi.pCode    = kKernels[k].spv;
        VkShaderModule mod;
        VK_CHECK(vkCreateShaderModule(ctx.device, &smi, nullptr, &mod));

        VkComputePipelineCreateInfo cpi{ VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO };
        cpi.stage.sType  = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
        cpi.stage.stage  = VK_SHADER_STAGE_COMPUTE_BIT;
        cpi.stage.module = mod;
        cpi.stage.pName  = "main";
        cpi.layout       = pipeLayout;
        VK_CHECK(vkCreateComputePipelines(ctx.device, VK_NULL_HANDLE, 1, &cpi, nullptr, &pipelines[k]));
        vkDestroyShaderModule(ctx.device, mod, nullptr);
    }
    printf("  Pipelines         : %u compiled in %.2f s\n",
           (unsigned)needed.size(), nowSeconds() - pipeT0);
    printf("\n");

    VkDescriptorPoolSize psz{ VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, 3 };
    VkDescriptorPoolCreateInfo dpi{ VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO };
    dpi.flags         = VK_DESCRIPTOR_POOL_CREATE_FREE_DESCRIPTOR_SET_BIT;
    dpi.maxSets       = 1;
    dpi.poolSizeCount = 1;
    dpi.pPoolSizes    = &psz;
    VkDescriptorPool descPool;
    VK_CHECK(vkCreateDescriptorPool(ctx.device, &dpi, nullptr, &descPool));

    FILE* csv = nullptr;
    if (!o.csvPath.empty()) {
        csv = fopen(o.csvPath.c_str(), "w");
        if (!csv) die("cannot open CSV file '%s'", o.csvPath.c_str());
        fprintf(csv, "device,m,n,k,kernel,a_source,b_source,a_layout,double_buffer,"
                     "b_split,tm,tn,block_m,block_n,lds_bytes,prefetch_regs,"
                     "run,gpu_ms,wall_ms,gflop,tflops\n");
    }

    // ---- per shape --------------------------------------------------------
    for (const Shape& shape : o.shapes) {
        const uint32_t M = shape.m, N = shape.n, K = shape.k;
        const size_t   elems = (size_t)M * N;
        const VkDeviceSize bytesC = (VkDeviceSize)elems * sizeof(float);
        const double   gflop = shape.gflop();

        // A block tile need not divide the matrix, so the grid is rounded up and
        // the edge workgroups read past M/N. The store is guarded, but the loads
        // are not, so A and B carry enough slack to keep those reads in bounds.
        uint32_t padRows = M, padCols = N;
        for (int kidx : o.kernels) {
            const KernelDesc& kd = kKernels[kidx];
            padRows = std::max(padRows, ((M + kd.blockM() - 1) / kd.blockM()) * kd.blockM());
            padCols = std::max(padCols, ((N + kd.blockN() - 1) / kd.blockN()) * kd.blockN());
        }
        // A row-major is read as A[row*K + k] with row < padRows; column-major as
        // A[k*M + row], whose furthest read is (K-1)*M + padRows-1. Allocate for
        // whichever is larger so either layout can be uploaded into the buffer.
        const size_t elemsA = std::max((size_t)padRows * K,
                                       (size_t)(K - 1) * M + padRows);
        // B is read as B[k*N + col] with k < K and col < padCols; the last row
        // is the only one that can overrun, by padCols-N elements.
        const size_t elemsB = (size_t)K * N + (padCols - N);
        const VkDeviceSize bytesA = (VkDeviceSize)elemsA * sizeof(float);
        const VkDeviceSize bytesB = (VkDeviceSize)elemsB * sizeof(float);
        const VkDeviceSize bytesStaging = std::max(std::max(bytesA, bytesB), bytesC);

        printf("======================================================================\n");
        printf(" A %ux%u * B %ux%u = C %ux%u      2*M*N*K = %.3f GFLOP\n",
               M, K, K, N, M, N, gflop);
        printf(" A %.2f MiB   B %.2f MiB   C %.2f MiB\n",
               (double)M * K * sizeof(float) / 1048576.0,
               (double)K * N * sizeof(float) / 1048576.0,
               bytesC / 1048576.0);
        if (padRows != M || padCols != N)
            printf(" grid padding: rows %u->%u, cols %u->%u (the largest block tile does not divide it)\n",
                   M, padRows, N, padCols);
        printf("======================================================================\n");
        fflush(stdout);

        Buffer bufA = createBuffer(ctx, bytesA, VK_BUFFER_USAGE_STORAGE_BUFFER_BIT | VK_BUFFER_USAGE_TRANSFER_DST_BIT,
                                   VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT, "matrix A");
        Buffer bufB = createBuffer(ctx, bytesB, VK_BUFFER_USAGE_STORAGE_BUFFER_BIT | VK_BUFFER_USAGE_TRANSFER_DST_BIT,
                                   VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT, "matrix B");
        Buffer bufC = createBuffer(ctx, bytesC, VK_BUFFER_USAGE_STORAGE_BUFFER_BIT | VK_BUFFER_USAGE_TRANSFER_SRC_BIT
                                              | VK_BUFFER_USAGE_TRANSFER_DST_BIT,
                                   VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT, "matrix C");
        Buffer staging = createBuffer(ctx, bytesStaging,
                                      VK_BUFFER_USAGE_TRANSFER_SRC_BIT | VK_BUFFER_USAGE_TRANSFER_DST_BIT,
                                      VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT,
                                      "staging");

        // Host copies are only kept when we verify, and hostA is always the
        // logical row-major matrix regardless of how the GPU copy is stored.
        std::vector<float> hostA, hostB, hostC, refC;
        if (o.check) { hostA.resize((size_t)M * K); hostB.resize(elemsB, 0.0f); }

        // A and B draw from separate seeded streams, so A can be regenerated in
        // either layout without keeping a second host copy of it.
        // Slack past the logical matrix is zeroed: the edge workgroups read it,
        // and stale garbage there could mean denormals in the FMA pipeline.
        auto uploadA = [&](bool colMajor) {
            std::mt19937 rng(o.seed);
            std::uniform_real_distribution<float> dist(-1.0f, 1.0f);
            float* p = (float*)staging.host;
            std::fill(p, p + elemsA, 0.0f);
            for (uint32_t m = 0; m < M; ++m) {
                for (uint32_t k = 0; k < K; ++k) {
                    float v = dist(rng);
                    p[colMajor ? (size_t)k * M + m : (size_t)m * K + k] = v;
                    if (o.check) hostA[(size_t)m * K + k] = v;
                }
            }
            submitOnce(ctx, [&](VkCommandBuffer cb) {
                VkBufferCopy c{ 0, 0, bytesA };
                vkCmdCopyBuffer(cb, staging.buf, bufA.buf, 1, &c);
            });
        };

        {   // B is row-major always, uploaded once.
            std::mt19937 rng(o.seed ^ 0x9E3779B9u);
            std::uniform_real_distribution<float> dist(-1.0f, 1.0f);
            float* p = (float*)staging.host;
            const size_t live = (size_t)K * N;
            for (size_t i = 0; i < live; ++i)      p[i] = dist(rng);
            for (size_t i = live; i < elemsB; ++i) p[i] = 0.0f;
            if (o.check) std::copy(p, p + elemsB, hostB.begin());
            submitOnce(ctx, [&](VkCommandBuffer cb) {
                VkBufferCopy c{ 0, 0, bytesB };
                vkCmdCopyBuffer(cb, staging.buf, bufB.buf, 1, &c);
            });
        }

        // Uploaded lazily below, whenever the running kernel wants a layout
        // different from the one currently resident.
        const char* residentALayout = nullptr;

        VkDescriptorSetAllocateInfo dsa{ VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO };
        dsa.descriptorPool     = descPool;
        dsa.descriptorSetCount = 1;
        dsa.pSetLayouts        = &setLayout;
        VkDescriptorSet dset;
        VK_CHECK(vkAllocateDescriptorSets(ctx.device, &dsa, &dset));

        VkDescriptorBufferInfo dbi[3] = {
            { bufA.buf, 0, VK_WHOLE_SIZE },
            { bufB.buf, 0, VK_WHOLE_SIZE },
            { bufC.buf, 0, VK_WHOLE_SIZE },
        };
        VkWriteDescriptorSet w[3]{};
        for (int i = 0; i < 3; ++i) {
            w[i].sType           = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
            w[i].dstSet          = dset;
            w[i].dstBinding      = (uint32_t)i;
            w[i].descriptorCount = 1;
            w[i].descriptorType  = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
            w[i].pBufferInfo     = &dbi[i];
        }
        vkUpdateDescriptorSets(ctx.device, 3, w, 0, nullptr);

        // One reusable command buffer holding exactly one dispatch.
        VkCommandBufferAllocateInfo cba{ VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO };
        cba.commandPool        = ctx.cmdPool;
        cba.level              = VK_COMMAND_BUFFER_LEVEL_PRIMARY;
        cba.commandBufferCount = 1;
        VkCommandBuffer cb;
        VK_CHECK(vkAllocateCommandBuffers(ctx.device, &cba, &cb));

        VkFenceCreateInfo fci{ VK_STRUCTURE_TYPE_FENCE_CREATE_INFO };
        VkFence fence;
        VK_CHECK(vkCreateFence(ctx.device, &fci, nullptr, &fence));

        const uint32_t pc[3] = { M, N, K };

        std::vector<RunStats> stats;

        for (size_t ki = 0; ki < o.kernels.size(); ++ki) {
            const int kidx = o.kernels[ki];
            const KernelDesc& kd = kKernels[kidx];

            if (!residentALayout || strcmp(residentALayout, kd.aLayout) != 0) {
                double t0 = nowSeconds();
                uploadA(kd.aCol());
                residentALayout = kd.aLayout;
                printf("-- A uploaded %s-major (%.2f s)\n", kd.aLayout, nowSeconds() - t0);
                fflush(stdout);
            }

            // Round up: the guarded store discards whatever falls outside M/N.
            const uint32_t gx = (N + kd.blockN() - 1) / kd.blockN();
            const uint32_t gy = (M + kd.blockM() - 1) / kd.blockM();

            // Record once, submit many times.
            VkCommandBufferBeginInfo bi{ VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO };
            VK_CHECK(vkResetCommandBuffer(cb, 0));
            VK_CHECK(vkBeginCommandBuffer(cb, &bi));
            if (haveTs) {
                vkCmdResetQueryPool(cb, ctx.queryPool, 0, 2);
                vkCmdWriteTimestamp(cb, VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT, ctx.queryPool, 0);
            }
            vkCmdBindPipeline(cb, VK_PIPELINE_BIND_POINT_COMPUTE, pipelines[kidx]);
            vkCmdBindDescriptorSets(cb, VK_PIPELINE_BIND_POINT_COMPUTE, pipeLayout, 0, 1, &dset, 0, nullptr);
            vkCmdPushConstants(cb, pipeLayout, VK_SHADER_STAGE_COMPUTE_BIT, 0, sizeof(pc), pc);
            vkCmdDispatch(cb, gx, gy, 1);
            if (haveTs)
                vkCmdWriteTimestamp(cb, VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT, ctx.queryPool, 1);
            VK_CHECK(vkEndCommandBuffer(cb));

            auto runOnce = [&](double* gpuMs, double* wallMs) {
                VK_CHECK(vkResetFences(ctx.device, 1, &fence));
                VkSubmitInfo si{ VK_STRUCTURE_TYPE_SUBMIT_INFO };
                si.commandBufferCount = 1;
                si.pCommandBuffers    = &cb;
                double t0 = nowSeconds();
                VK_CHECK(vkQueueSubmit(ctx.queue, 1, &si, fence));
                VK_CHECK(vkWaitForFences(ctx.device, 1, &fence, VK_TRUE, UINT64_MAX));
                double t1 = nowSeconds();
                if (wallMs) *wallMs = (t1 - t0) * 1e3;
                if (gpuMs && haveTs) {
                    uint64_t ts[2] = { 0, 0 };
                    VkResult r = vkGetQueryPoolResults(ctx.device, ctx.queryPool, 0, 2, sizeof(ts), ts,
                                                       sizeof(uint64_t),
                                                       VK_QUERY_RESULT_64_BIT | VK_QUERY_RESULT_WAIT_BIT);
                    if (r == VK_SUCCESS) {
                        uint64_t mask = (ctx.timestampValidBits >= 64) ? ~0ull
                                                                       : ((1ull << ctx.timestampValidBits) - 1ull);
                        uint64_t d = (ts[1] & mask) - (ts[0] & mask);
                        *gpuMs = (double)d * tsPeriodNs / 1e6;
                    } else {
                        *gpuMs = -1.0;
                    }
                }
            };

            printf("[%-9s %ux%u A-%s %-6s %-4s]  A:%s  B:%s  block %ux%u  grid %ux%u  "
                   "LDS %uB  prefetch %u regs\n",
                   kd.name, kd.tm, kd.tn, kd.aLayout, kd.db ? "db" : "single",
                   kd.bsplit ? "bs4" : "bs-",
                   kd.aSrc, kd.bSrc, kd.blockM(), kd.blockN(), gx, gy,
                   kd.ldsBytes(), kd.prefetchRegs());

            for (int w2 = 0; w2 < o.warmup; ++w2) runOnce(nullptr, nullptr);

            RunStats rs;
            rs.kernel = kidx;
            for (int it = 0; it < o.iters; ++it) {
                double g = -1.0, wm = 0.0;
                runOnce(&g, &wm);
                double t = (g > 0.0) ? g : wm;
                if (g > 0.0) rs.gpuMs.push_back(g);
                rs.wallMs.push_back(wm);
                char gpuStr[24];
                if (g > 0.0) snprintf(gpuStr, sizeof(gpuStr), "%9.3f", g);
                else         snprintf(gpuStr, sizeof(gpuStr), "%9s", "n/a");
                printf("    run %d/%d   gpu %s ms   wall %9.3f ms   %8.4f TFLOPS\n",
                       it + 1, o.iters, gpuStr, wm, tflops(gflop, t));
                fflush(stdout);
                if (csv)
                    fprintf(csv, "%s,%u,%u,%u,%s,%s,%s,%s,%u,%u,%u,%u,%u,%u,%u,%u,%d,%.6f,%.6f,%.3f,%.6f\n",
                            ctx.props.deviceName, M, N, K, kd.name, kd.aSrc, kd.bSrc, kd.aLayout,
                            kd.db, kd.bsplit, kd.tm, kd.tn, kd.blockM(), kd.blockN(),
                            kd.ldsBytes(), kd.prefetchRegs(), it + 1,
                            g, wm, gflop, tflops(gflop, t));
            }

            // ---- verification ------------------------------------------------
            if (o.check) {
                hostC.resize(elems);
                submitOnce(ctx, [&](VkCommandBuffer c) {
                    VkBufferMemoryBarrier bm{ VK_STRUCTURE_TYPE_BUFFER_MEMORY_BARRIER };
                    bm.srcAccessMask       = VK_ACCESS_SHADER_WRITE_BIT;
                    bm.dstAccessMask       = VK_ACCESS_TRANSFER_READ_BIT;
                    bm.srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
                    bm.dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
                    bm.buffer              = bufC.buf;
                    bm.size                = VK_WHOLE_SIZE;
                    vkCmdPipelineBarrier(c, VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT, VK_PIPELINE_STAGE_TRANSFER_BIT,
                                         0, 0, nullptr, 1, &bm, 0, nullptr);
                    VkBufferCopy cp{ 0, 0, bytesC };
                    vkCmdCopyBuffer(c, bufC.buf, staging.buf, 1, &cp);
                });
                memcpy(hostC.data(), staging.host, (size_t)bytesC);

                // fp32 dot product of length K, |a|,|b| <= 1 -> error grows ~ sqrt(K)*eps.
                const double atol = 1e-2, rtol = 1e-4;
                double t0 = nowSeconds();
                rs.check = o.fullCheck
                         ? checkFull(hostA.data(), hostB.data(), hostC.data(), M, N, K, atol, rtol)
                         : checkSampled(hostA.data(), hostB.data(), hostC.data(), M, N, K,
                                        o.samples, o.seed, atol, rtol);
                double t1 = nowSeconds();
                rs.checked = true;

                printf("    verify   %s   compared %llu elems in %.2f s | max_abs %.3e  max_rel %.3e  rms %.3e",
                       rs.check.pass ? "PASS" : "*** FAIL ***",
                       (unsigned long long)rs.check.compared, t1 - t0,
                       rs.check.maxAbs, rs.check.maxRel, rs.check.rms);
                if (!rs.check.pass) printf("  (%llu bad)", (unsigned long long)rs.check.bad);
                printf("\n");

                // All four kernels accumulate in the same order, so they should
                // agree bit-for-bit. Comparing them catches races the sampled
                // CPU reference could miss.
                if (refC.empty()) {
                    refC = hostC;
                } else {
                    double mx = 0.0;
                    bool exact = true;
                    for (size_t i = 0; i < elems; ++i) {
                        if (refC[i] != hostC[i]) exact = false;
                        mx = std::max(mx, (double)std::fabs(refC[i] - hostC[i]));
                    }
                    rs.bitExactVsFirst = exact;
                    rs.maxDiffVsFirst  = mx;
                    printf("    vs %-9s %s   max_diff %.3e\n",
                           kKernels[o.kernels[0]].name,
                           exact ? "bit-exact" : "differs  ", mx);
                }
                fflush(stdout);
            }

            stats.push_back(rs);
            printf("\n");
        }

        // ---- summary ------------------------------------------------------
        struct Row {
            const KernelDesc* kd;
            double best, med, avg, wallBest;
        };
        std::vector<Row> rows;
        for (const RunStats& rs : stats) {
            const std::vector<double>& t = rs.gpuMs.empty() ? rs.wallMs : rs.gpuMs;
            Row r;
            r.kd   = &kKernels[rs.kernel];
            r.best = *std::min_element(t.begin(), t.end());
            r.med  = median(t);
            r.avg  = 0.0;
            for (double x : t) r.avg += x;
            r.avg /= (double)t.size();
            // Wall-clock TFLOPS is carried alongside so a bogus timestampPeriod
            // or query result shows up as a mismatch instead of a GPU verdict.
            r.wallBest = *std::min_element(rs.wallMs.begin(), rs.wallMs.end());
            rows.push_back(r);
        }

        const char* kSep =
            "-----------------------------------------------------------------------------------------------------\n";
        printf("%s", kSep);
        printf(" summary  A %ux%u * B %ux%u   (%.3f GFLOP per GEMM, %d runs, ranked by best time)\n",
               M, K, K, N, gflop, o.iters);
        printf("%s", kSep);
        printf(" %4s %-10s %5s %-9s %-16s %6s %7s %6s %9s %9s %10s %8s\n",
               "rank", "kernel", "tile", "block", "A / B", "A-ord", "dbuf", "bsplit",
               "best_ms", "med_ms", "TFLOPS_bst", "vs best");
        printf("%s", kSep);

        // Rank by best time. The FLOP count is the logical 2*M*N*K, so a tiling
        // whose block does not divide the matrix is charged for the work it
        // wastes on the padded edge rather than credited for it.
        std::vector<size_t> order(rows.size());
        for (size_t i = 0; i < order.size(); ++i) order[i] = i;
        std::stable_sort(order.begin(), order.end(),
                         [&](size_t a, size_t b) { return rows[a].best < rows[b].best; });

        const double topBest = rows.empty() ? 0.0 : rows[order[0]].best;
        for (size_t r = 0; r < order.size(); ++r) {
            const Row& row = rows[order[r]];
            const KernelDesc& kd = *row.kd;
            char tile[12], block[12], ab[32];
            snprintf(tile,  sizeof(tile),  "%ux%u", kd.tm, kd.tn);
            snprintf(block, sizeof(block), "%ux%u", kd.blockM(), kd.blockN());
            snprintf(ab,    sizeof(ab),    "%s / %s", kd.aSrc, kd.bSrc);
            printf(" %4zu %-10s %5s %-9s %-16s %6s %7s %6s %9.3f %9.3f %10.4f %7.2fx\n",
                   r + 1, kd.name, tile, block, ab, kd.aLayout,
                   kd.db ? "on" : "off", kd.bsplit ? "on" : "off", row.best, row.med,
                   tflops(gflop, row.best), topBest / row.best);
        }
        printf("%s", kSep);
        if (!rows.empty()) {
            const Row& w = rows[order[0]];
            printf(" BEST at %ux%ux%u: %s  tile %ux%u  A %s-major  double-buffer %s"
                   "  B-split %s  (block %ux%u, A:%s B:%s)  %.3f ms  %.4f TFLOPS\n",
                   M, K, N, w.kd->name, w.kd->tm, w.kd->tn, w.kd->aLayout,
                   w.kd->db ? "on" : "off", w.kd->bsplit ? "on" : "off",
                   w.kd->blockM(), w.kd->blockN(),
                   w.kd->aSrc, w.kd->bSrc, w.best, tflops(gflop, w.best));
        }
        printf(" timing source: %s\n", haveTs ? "GPU timestamps" : "wall clock (submit->fence)");
        if (o.check) {
            printf(" verification : ");
            bool allPass = true;
            for (const RunStats& rs : stats) allPass = allPass && (!rs.checked || rs.check.pass);
            printf("%s\n", allPass ? "ALL KERNELS PASS" : "*** SOME KERNELS FAILED ***");
        }
        printf("\n");
        fflush(stdout);

        vkDestroyFence(ctx.device, fence, nullptr);
        vkFreeCommandBuffers(ctx.device, ctx.cmdPool, 1, &cb);
        VK_CHECK(vkFreeDescriptorSets(ctx.device, descPool, 1, &dset));
        destroyBuffer(ctx, staging);
        destroyBuffer(ctx, bufC);
        destroyBuffer(ctx, bufB);
        destroyBuffer(ctx, bufA);
    }

    if (csv) fclose(csv);

    for (int k : needed) vkDestroyPipeline(ctx.device, pipelines[k], nullptr);
    vkDestroyDescriptorPool(ctx.device, descPool, nullptr);
    vkDestroyPipelineLayout(ctx.device, pipeLayout, nullptr);
    vkDestroyDescriptorSetLayout(ctx.device, setLayout, nullptr);
    if (ctx.queryPool) vkDestroyQueryPool(ctx.device, ctx.queryPool, nullptr);
    vkDestroyCommandPool(ctx.device, ctx.cmdPool, nullptr);
    vkDestroyDevice(ctx.device, nullptr);
    vkDestroyInstance(ctx.instance, nullptr);
    return 0;
}
